"use client";

import React, {
  createContext,
  useContext,
  useState,
  useEffect,
  useCallback,
  type ReactNode,
} from "react";
import Cookies from "js-cookie";

type Language = "en" | "ar";

interface Translations {
  [key: string]: string;
}

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
  localize: (english?: string | null, arabic?: string | null) => string;
  dir: "ltr" | "rtl";
  isRTL: boolean;
}

const LanguageContext = createContext<LanguageContextType | undefined>(
  undefined,
);

// English translations
const en: Translations = {
  // Nav
  "nav.home": "Home",
  "nav.products": "Products",
  "nav.services": "Services",
  "nav.about": "About",
  "nav.contact": "Contact",
  "nav.faq": "FAQ",
  "nav.requestService": "Request Service",
  "nav.login": "Login",
  "nav.register": "Register",
  "nav.myOrders": "My Orders",
  "nav.myAddresses": "My Addresses",
  "nav.profile": "Profile",
  "nav.logout": "Logout",

  // Home
  "home.hero.headline": "Authorized Carrier & Midea Dealer",
  "home.seoTitle": "Lord AC — Authorized Carrier & Midea Dealer",
  "home.seoDescription":
    "Lord Air Conditioning — Authorized Carrier & Midea dealer in Egypt since 1986.",
  "home.hero.tagline": "Air Conditioning — Since 1986",
  "home.hero.shopNow": "Shop Now",
  "home.hero.ourServices": "Our Services",
  "home.hero.authorized": "Authorized",
  "home.featured.title": "Featured Products",
  "home.featured.viewAll": "View All Products",
  "home.services.title": "Our Services",
  "home.services.learnMore": "Learn More",
  "home.why.title": "Why Choose Lord",
  "home.why.since": "Since",
  "home.why.unitsInstalled": "Units Installed",
  "home.why.authorizedDealer": "Authorized Dealer",
  "home.why.afterSalesSupport": "After-Sales Support",
  "home.why.brandsSuffix": " Brands",
  "home.testimonials.title": "What Our Customers Say",
  "home.cta.headline": "Need help choosing? Request a free consultation",
  "home.cta.button": "Contact Us",

  // Products
  "products.title": "Our Products",
  "products.showing": "Showing {count} of {total} products",
  "products.filter": "Filter",
  "products.clearFilters": "Clear All Filters",
  "products.sort": "Sort By",
  "products.sortDefault": "Default",
  "products.sortPriceLow": "Price: Low to High",
  "products.sortPriceHigh": "Price: High to Low",
  "products.sortName": "Name: A–Z",
  "products.sortNameAZ": "Name: A–Z",
  "products.sortNewest": "Newest First",
  "products.addToCart": "Add to Cart",
  "products.outOfStock": "Out of Stock",
  "products.quickView": "Quick View",
  "products.viewDetails": "View Full Details",
  "products.inStock": "In Stock",
  "products.buyNow": "Buy Now",
  "products.added": "Added!",
  "products.addedToCart": "Added to Cart",
  "products.quantity": "Quantity",
  "products.inquireWhatsApp": "Ask on WhatsApp",
  "products.description": "Description",
  "products.features": "Features",
  "products.specifications": "Specifications",
  "products.relatedProducts": "Related Products",
  "products.warranty": "Warranty included",
  "products.freeDelivery": "Free delivery",
  "products.authorizedDealer": "Authorized dealer",
  "products.genuineParts": "Genuine parts",
  "products.brands": "Brands",
  "products.allBrands": "All brands",
  "products.categories": "Categories",
  "products.model": "Model",
  "products.relatedTitle": "You May Also Like",

  // Cart
  "cart.title": "Shopping Cart",
  "cart.empty": "Your cart is empty",
  "cart.browseProducts": "Browse Products",
  "cart.subtotal": "Subtotal",
  "cart.shipping": "Shipping",
  "cart.discount": "Discount",
  "cart.total": "Total",
  "cart.free": "Free",
  "cart.couponPlaceholder": "Enter coupon code",
  "cart.applyCoupon": "Apply",
  "cart.removeCoupon": "Remove",
  "cart.proceedCheckout": "Proceed to Checkout",
  "cart.continueShopping": "Continue Shopping",
  "cart.remove": "Remove from cart?",
  "cart.viewCart": "View Cart",
  "cart.checkout": "Checkout",
  "cart.apply": "Apply",
  "cart.clearAll": "Clear All",
  "cart.emptyMessage": "Add products to your cart to continue shopping.",
  "cart.freeShipping": "Free Shipping",
  "cart.orderSummary": "Order Summary",

  // Checkout
  "checkout.title": "Checkout",
  "checkout.shipping": "Shipping",
  "checkout.review": "Review",
  "checkout.payment": "Payment",
  "checkout.confirmation": "Confirmation",
  "checkout.guestCheckout": "Checkout as Guest",
  "checkout.continueReview": "Continue to Review",
  "checkout.backToCart": "Back to Cart",
  "checkout.proceedPayment": "Proceed to Payment",
  "checkout.shippingAddress": "Shipping Address",
  "checkout.addNewAddress": "Add New Address",
  "checkout.addressLine1": "Address Line 1",
  "checkout.addressLine2": "Address Line 2",
  "checkout.city": "City",
  "checkout.governorate": "Governorate",
  "checkout.phone": "Phone",
  "checkout.continue": "Continue",
  "checkout.reviewOrder": "Review Order",
  "checkout.back": "Back",
  "checkout.proceedToPayment": "Proceed to Payment",
  "checkout.paymobInfo": "Secure online payment",
  "checkout.paymobDesc": "You will be redirected to complete your payment securely.",
  "checkout.placeOrder": "Place Order",
  "checkout.guestNote": "You can create an account later to track orders faster.",
  "checkout.orderError": "Could not place your order. Please try again.",
  "checkout.paymobAccept": "Paymob Accept",

  // Auth
  "auth.login": "Login",
  "auth.register": "Create Account",
  "auth.forgotPassword": "Forgot Password?",
  "auth.noAccount": "Don't have an account?",
  "auth.hasAccount": "Already have an account?",
  "auth.verifyEmail": "Verify Your Email",
  "auth.resendCode": "Resend Code",
  "auth.email": "Email",
  "auth.password": "Password",
  "auth.confirmPassword": "Confirm Password",
  "auth.newPassword": "New Password",
  "auth.name": "Name",
  "auth.phone": "Phone",
  "auth.nationalId": "National ID",
  "auth.loginSubtitle": "Sign in to manage your orders and addresses.",
  "auth.registerSubtitle": "Create an account to shop and track your orders.",
  "auth.loginSuccess": "Logged in successfully.",
  "auth.loginError": "Could not log in. Please check your details.",
  "auth.registerSuccess": "Account created successfully.",
  "auth.registerError": "Could not create account. Please try again.",
  "auth.forgotPasswordDesc": "Enter your email and we'll send a reset code.",
  "auth.sendResetCode": "Send Reset Code",
  "auth.backToLogin": "Back to Login",
  "auth.resetPassword": "Reset Password",
  "auth.resetPasswordDesc": "Enter the code sent to",
  "auth.otpCode": "Verification Code",
  "auth.forgotPasswordError": "Could not send reset code.",
  "auth.passwordResetSuccess": "Password reset successfully.",
  "auth.passwordResetDesc": "You can now log in with your new password.",
  "auth.resetError": "Could not reset password.",
  "auth.emailVerified": "Email verified",
  "auth.redirecting": "Redirecting...",
  "auth.verifyEmailDescription": "Verify your email address",
  "auth.verify": "Verify",
  "auth.noCode": "Didn't receive a code?",
  "auth.resendOtp": "Resend code",
  "auth.verifySuccess": "Email verified successfully.",
  "auth.verifyError": "Invalid verification code.",
  "auth.otpResent": "Verification code resent.",
  "auth.resendError": "Could not resend code.",
  "auth.otpSent": "We sent a verification code to",

  // Account
  "account.welcome": "Welcome back",
  "account.orders": "My Orders",
  "account.addresses": "My Addresses",
  "account.profile": "My Profile",
  "account.changePassword": "Change Password",
  "account.noOrders": "No orders yet",
  "account.startShopping": "Start Shopping",
  "account.logout": "Logout",
  "account.ordersDesc": "View and track your orders",
  "account.addressesDesc": "Manage your delivery addresses",
  "account.profileDesc": "Update your personal information",
  "account.dashboardDesc": "Manage your account, orders, and saved addresses.",
  "account.recentOrders": "Recent Orders",
  "account.viewAll": "View All",
  "account.items": "items",
  "account.personalInfo": "Personal Information",
  "account.profileUpdated": "Profile updated successfully.",
  "account.currentPassword": "Current Password",
  "account.passwordChanged": "Password changed successfully.",
  "account.passwordError": "Could not change password.",
  "account.addAddress": "Add Address",
  "account.editAddress": "Edit Address",
  "account.addressAdded": "Address added successfully.",
  "account.addressUpdated": "Address updated successfully.",
  "account.addressDeleted": "Address deleted successfully.",
  "account.confirmDelete": "Are you sure you want to delete this address?",
  "account.maxAddresses": "You can save multiple delivery addresses.",
  "account.noAddresses": "No addresses saved yet.",
  "account.label": "Label",
  "account.home": "Home",
  "account.office": "Office",
  "account.recipientName": "Recipient Name",
  "account.postalCode": "Postal Code",
  "account.setDefaultAddress": "Set as default address",
  "account.backToOrders": "Back to orders",
  "account.statusHistory": "Status History",
  "account.paidOn": "Paid on {date}",

  // General
  "general.loading": "Loading...",
  "general.error": "Something went wrong",
  "general.retry": "Retry",
  "general.save": "Save Changes",
  "general.cancel": "Cancel",
  "general.delete": "Delete",
  "general.edit": "Edit",
  "general.close": "Close",
  "general.back": "Back",
  "general.next": "Next",
  "general.submit": "Submit",
  "general.search": "Search",
  "general.noResults": "No results found",
  "general.currency": "EGP",
  "general.loadingShort": "Loading...",
  "general.whatsapp": "WhatsApp",
  "general.facebook": "Facebook",
  "general.instagram": "Instagram",
  "general.breadcrumb": "Breadcrumb",
  "general.closeCart": "Close cart",
  "general.removeItem": "Remove item",
  "general.decreaseQuantity": "Decrease quantity",
  "general.increaseQuantity": "Increase quantity",
  "general.chatOnWhatsApp": "Chat on WhatsApp",
  "general.toggleMenu": "Toggle menu",
  "general.product": "Product",
  "general.quantityShort": "Qty",
  "general.select": "Select",
  "general.other": "Other",
  "general.pending": "Pending",

  // Footer
  "footer.quickLinks": "Quick Links",
  "footer.services": "Services",
  "footer.contactInfo": "Contact Info",
  "footer.copyright": "© 2026 Lord Air Conditioning",
  "footer.allRights": "All rights reserved.",
  "footer.description":
    "Authorized Carrier & Midea Dealer. Air Conditioning solutions since 1986.",
  "footer.service.installation": "Installation",
  "footer.service.maintenance": "Maintenance",
  "footer.service.repair": "Repair",
  "footer.service.delivery": "Delivery",
  "footer.service.spareParts": "Spare Parts",
  "legal.privacyPolicy": "Privacy Policy",
  "legal.termsConditions": "Terms and Conditions",

  // Services page
  "services.title": "Our Services",
  "services.tagline": "Complete after-sales support for your air conditioning",
  "services.subtitle": "Installation, maintenance, repair, and support from Lord AC specialists.",
  "services.requestService": "Request This Service",
  "services.urgentCta": "Need urgent service? Call us now",
  "services.ctaTitle": "Need help with your AC?",
  "services.ctaSubtitle": "Send us a service request and our team will contact you.",
  "services.chatWhatsApp": "Chat on WhatsApp",
  "services.requestSubmitted": "Service request submitted",
  "services.requestDesc": "We received your request and will contact you soon.",
  "services.submitAnother": "Submit Another Request",
  "services.requestFormDesc": "Tell us what you need and we will arrange the right support.",
  "services.serviceType": "Service Type",
  "services.acBrand": "AC Brand",
  "services.installationAddress": "Installation Address",
  "services.preferredDate": "Preferred Date",
  "services.description": "Description",
  "services.descriptionPlaceholder": "Describe the issue or service you need...",
  "services.submitRequest": "Submit Request",
  "services.selectServiceType": "Select service type",
  "services.selectBrand": "Select brand",
  "services.otherBrand": "Other",
  "services.installationAddressPlaceholder": "Full installation address",

  // Contact page
  "contact.title": "Contact Us",
  "contact.sendMessage": "Send Message",
  "contact.thankYou": "Thank you! We'll contact you within 1 hour.",
  "contact.getDirections": "Get Directions",
  "contact.subtitle": "We're here to help with products, installation, maintenance, and support.",
  "contact.address": "Address",
  "contact.phone": "Phone",
  "contact.whatsapp": "WhatsApp",
  "contact.email": "Email",
  "contact.workingHours": "Working Hours",
  "contact.formTitle": "Send us a message",
  "contact.name": "Name",
  "contact.namePlaceholder": "Your full name",
  "contact.emailPlaceholder": "you@example.com",
  "contact.inquiryType": "Inquiry Type",
  "contact.inquiryTypes.general": "General Inquiry",
  "contact.inquiryTypes.purchase": "Purchase",
  "contact.inquiryTypes.installation": "Installation",
  "contact.inquiryTypes.maintenance": "Maintenance",
  "contact.inquiryTypes.orderSupport": "Order Support",
  "contact.message": "Message",
  "contact.messagePlaceholder": "How can we help?",
  "contact.send": "Send Message",
  "contact.successMessage": "Message sent successfully.",
  "contact.errorMessage": "Could not send message. Please try again.",
  "contact.mapTitle": "Lord Location",

  // FAQ page
  "faq.title": "Frequently Asked Questions",
  "faq.cantFind": "Can't find your answer?",
  "faq.subtitle": "Answers to common questions about products, installation, and support.",
  "faq.searchPlaceholder": "Search questions...",
  "faq.ctaTitle": "Still need help?",
  "faq.ctaSubtitle": "Contact our team and we will help you choose the right solution.",
  "faq.chatWithUs": "Chat with us",

  // Order
  "order.confirmed": "Confirmed",
  "order.processing": "Processing",
  "order.shipped": "Shipped",
  "order.delivered": "Delivered",
  "order.cancelled": "Cancelled",
  "order.refunded": "Refunded",
  "order.pendingPayment": "Pending Payment",
  "order.orderPlaced": "Order Placed",
  "order.cancelOrder": "Cancel Order",
  "order.trackOrder": "Track My Order",
  "order.enterOrderId": "Enter order number",
  "order.track": "Track",
  "order.trackDesc": "Enter your order number to view its latest status.",
  "order.notFound": "Order not found",
  "order.items": "Order Items",

  // Order Confirmation
  "orderConfirmation.title": "Order placed successfully!",
  "orderConfirmation.subtitle": "Thank you for your order. We'll keep you updated.",
  "orderConfirmation.orderId": "Order ID",
  "orderConfirmation.emailSent": "Confirmation email sent to",
  "orderConfirmation.estimatedDelivery":
    "Estimated delivery: 3–5 business days",
  "orderConfirmation.continueShopping": "Continue Shopping",
  "orderConfirmation.viewOrders": "View My Orders",

  // About
  "about.title": "About Lord",
  "about.subtitle": "Authorized AC solutions, installation, and support since 1986.",
  "about.storyTitle": "Our Story",
  "about.missionTitle": "Our Mission",
  "about.visionTitle": "Our Vision",
  "about.authorizedTitle": "Authorized Carrier & Midea Dealer",
  "about.authorizedDesc":
    "We provide original products, professional installation, and reliable after-sales support.",
  "about.yearsExperience": "Years Experience",
  "about.happyCustomers": "Happy Customers",
  "about.governorates": "Governorates",
  "about.rating": "Customer Rating",
};

// Arabic translations
const ar: Translations = {
  "nav.home": "الرئيسية",
  "nav.products": "المنتجات",
  "nav.services": "الخدمات",
  "nav.about": "من نحن",
  "nav.contact": "اتصل بنا",
  "nav.faq": "الأسئلة الشائعة",
  "nav.requestService": "طلب خدمة",
  "nav.login": "تسجيل الدخول",
  "nav.register": "إنشاء حساب",
  "nav.myOrders": "طلباتي",
  "nav.myAddresses": "عناويني",
  "nav.profile": "الملف الشخصي",
  "nav.logout": "تسجيل الخروج",

  "home.hero.headline": "وكيل معتمد لكاريير وميديا",
  "home.seoTitle": "لورد للتكييف — وكيل معتمد لكاريير وميديا",
  "home.seoDescription":
    "لورد لتكييف الهواء — وكيل معتمد لكاريير وميديا في مصر منذ ١٩٨٦.",
  "home.hero.tagline": "تكييف الهواء — منذ ١٩٨٦",
  "home.hero.shopNow": "تسوق الآن",
  "home.hero.ourServices": "خدماتنا",
  "home.hero.authorized": "معتمد",
  "home.featured.title": "منتجات مميزة",
  "home.featured.viewAll": "عرض جميع المنتجات",
  "home.services.title": "خدماتنا",
  "home.services.learnMore": "اعرف المزيد",
  "home.why.title": "لماذا تختار لورد",
  "home.why.since": "منذ",
  "home.why.unitsInstalled": "وحدة تم تركيبها",
  "home.why.authorizedDealer": "وكيل معتمد",
  "home.why.afterSalesSupport": "دعم ما بعد البيع",
  "home.why.brandsSuffix": " علامات",
  "home.testimonials.title": "ماذا يقول عملاؤنا",
  "home.cta.headline": "تحتاج مساعدة في الاختيار؟ اطلب استشارة مجانية",
  "home.cta.button": "اتصل بنا",

  "products.title": "منتجاتنا",
  "products.showing": "عرض {count} من {total} منتج",
  "products.filter": "تصفية",
  "products.clearFilters": "مسح جميع الفلاتر",
  "products.sort": "ترتيب حسب",
  "products.sortDefault": "الافتراضي",
  "products.sortPriceLow": "السعر: من الأقل إلى الأعلى",
  "products.sortPriceHigh": "السعر: من الأعلى إلى الأقل",
  "products.sortName": "الاسم: أ–ي",
  "products.sortNameAZ": "الاسم: أ–ي",
  "products.sortNewest": "الأحدث أولاً",
  "products.addToCart": "أضف إلى السلة",
  "products.outOfStock": "نفذ من المخزون",
  "products.quickView": "عرض سريع",
  "products.viewDetails": "عرض التفاصيل الكاملة",
  "products.inStock": "متوفر",
  "products.buyNow": "اشتري الآن",
  "products.added": "تمت الإضافة!",
  "products.addedToCart": "تمت الإضافة إلى السلة",
  "products.quantity": "الكمية",
  "products.inquireWhatsApp": "استفسر عبر واتساب",
  "products.description": "الوصف",
  "products.features": "المميزات",
  "products.specifications": "المواصفات",
  "products.relatedProducts": "منتجات ذات صلة",
  "products.warranty": "الضمان شامل",
  "products.freeDelivery": "توصيل مجاني",
  "products.authorizedDealer": "وكيل معتمد",
  "products.genuineParts": "قطع غيار أصلية",
  "products.brands": "العلامات التجارية",
  "products.allBrands": "كل العلامات",
  "products.categories": "التصنيفات",
  "products.model": "الموديل",
  "products.relatedTitle": "قد يعجبك أيضاً",

  "cart.title": "سلة التسوق",
  "cart.empty": "سلة التسوق فارغة",
  "cart.browseProducts": "تصفح المنتجات",
  "cart.subtotal": "المجموع الفرعي",
  "cart.shipping": "الشحن",
  "cart.discount": "الخصم",
  "cart.total": "الإجمالي",
  "cart.free": "مجاني",
  "cart.couponPlaceholder": "أدخل كود الخصم",
  "cart.applyCoupon": "تطبيق",
  "cart.removeCoupon": "إزالة",
  "cart.proceedCheckout": "متابعة الشراء",
  "cart.continueShopping": "متابعة التسوق",
  "cart.remove": "إزالة من السلة؟",
  "cart.viewCart": "عرض السلة",
  "cart.checkout": "الدفع",
  "cart.apply": "تطبيق",
  "cart.clearAll": "مسح الكل",
  "cart.emptyMessage": "أضف منتجات إلى السلة لمتابعة التسوق.",
  "cart.freeShipping": "شحن مجاني",
  "cart.orderSummary": "ملخص الطلب",

  "checkout.title": "إتمام الشراء",
  "checkout.shipping": "الشحن",
  "checkout.review": "المراجعة",
  "checkout.payment": "الدفع",
  "checkout.confirmation": "التأكيد",
  "checkout.guestCheckout": "الشراء كضيف",
  "checkout.continueReview": "متابعة إلى المراجعة",
  "checkout.backToCart": "العودة إلى السلة",
  "checkout.proceedPayment": "متابعة إلى الدفع",
  "checkout.shippingAddress": "عنوان الشحن",
  "checkout.addNewAddress": "إضافة عنوان جديد",
  "checkout.addressLine1": "العنوان الأول",
  "checkout.addressLine2": "العنوان الثاني",
  "checkout.city": "المدينة",
  "checkout.governorate": "المحافظة",
  "checkout.phone": "الهاتف",
  "checkout.continue": "متابعة",
  "checkout.reviewOrder": "مراجعة الطلب",
  "checkout.back": "رجوع",
  "checkout.proceedToPayment": "متابعة إلى الدفع",
  "checkout.paymobInfo": "دفع إلكتروني آمن",
  "checkout.paymobDesc": "سيتم تحويلك لإتمام الدفع بأمان.",
  "checkout.placeOrder": "تأكيد الطلب",
  "checkout.guestNote": "يمكنك إنشاء حساب لاحقاً لتتبع الطلبات بشكل أسرع.",
  "checkout.orderError": "تعذر إنشاء الطلب. حاول مرة أخرى.",
  "checkout.paymobAccept": "باي موب أكسبت",

  "auth.login": "تسجيل الدخول",
  "auth.register": "إنشاء حساب",
  "auth.forgotPassword": "نسيت كلمة المرور؟",
  "auth.noAccount": "ليس لديك حساب؟",
  "auth.hasAccount": "لديك حساب بالفعل؟",
  "auth.verifyEmail": "تأكيد البريد الإلكتروني",
  "auth.resendCode": "إعادة إرسال الكود",
  "auth.email": "البريد الإلكتروني",
  "auth.password": "كلمة المرور",
  "auth.confirmPassword": "تأكيد كلمة المرور",
  "auth.newPassword": "كلمة المرور الجديدة",
  "auth.name": "الاسم",
  "auth.phone": "الهاتف",
  "auth.nationalId": "الرقم القومي",
  "auth.loginSubtitle": "سجل الدخول لإدارة طلباتك وعناوينك.",
  "auth.registerSubtitle": "أنشئ حساباً للتسوق وتتبع طلباتك.",
  "auth.loginSuccess": "تم تسجيل الدخول بنجاح.",
  "auth.loginError": "تعذر تسجيل الدخول. تحقق من البيانات.",
  "auth.registerSuccess": "تم إنشاء الحساب بنجاح.",
  "auth.registerError": "تعذر إنشاء الحساب. حاول مرة أخرى.",
  "auth.forgotPasswordDesc": "أدخل بريدك الإلكتروني وسنرسل كود إعادة التعيين.",
  "auth.sendResetCode": "إرسال كود التعيين",
  "auth.backToLogin": "العودة لتسجيل الدخول",
  "auth.resetPassword": "إعادة تعيين كلمة المرور",
  "auth.resetPasswordDesc": "أدخل الكود المرسل إلى",
  "auth.otpCode": "كود التحقق",
  "auth.otpSent": "تم إرسال كود التحقق إلى",
  "auth.forgotPasswordError": "تعذر إرسال كود إعادة التعيين.",
  "auth.passwordResetSuccess": "تم تغيير كلمة المرور بنجاح.",
  "auth.passwordResetDesc": "يمكنك الآن تسجيل الدخول بكلمة المرور الجديدة.",
  "auth.resetError": "تعذر تغيير كلمة المرور.",
  "auth.emailVerified": "تم تأكيد البريد الإلكتروني",
  "auth.redirecting": "جاري التحويل...",
  "auth.verifyEmailDescription": "تأكيد عنوان بريدك الإلكتروني",
  "auth.verify": "تأكيد",
  "auth.noCode": "لم يصلك الكود؟",
  "auth.resendOtp": "إعادة إرسال الكود",
  "auth.verifySuccess": "تم تأكيد البريد الإلكتروني بنجاح.",
  "auth.verifyError": "كود التحقق غير صحيح.",
  "auth.otpResent": "تمت إعادة إرسال كود التحقق.",
  "auth.resendError": "تعذر إعادة إرسال الكود.",

  "account.welcome": "مرحباً بك",
  "account.orders": "طلباتي",
  "account.addresses": "عناويني",
  "account.profile": "ملفي الشخصي",
  "account.changePassword": "تغيير كلمة المرور",
  "account.noOrders": "لا توجد طلبات بعد",
  "account.startShopping": "ابدأ التسوق",
  "account.logout": "تسجيل الخروج",
  "account.ordersDesc": "عرض وتتبع طلباتك",
  "account.addressesDesc": "إدارة عناوين التوصيل",
  "account.profileDesc": "تحديث بياناتك الشخصية",
  "account.dashboardDesc": "إدارة حسابك وطلباتك وعناوينك المحفوظة.",
  "account.recentOrders": "أحدث الطلبات",
  "account.viewAll": "عرض الكل",
  "account.items": "عناصر",
  "account.personalInfo": "البيانات الشخصية",
  "account.profileUpdated": "تم تحديث الملف الشخصي.",
  "account.currentPassword": "كلمة المرور الحالية",
  "account.passwordChanged": "تم تغيير كلمة المرور بنجاح.",
  "account.passwordError": "تعذر تغيير كلمة المرور.",
  "account.addAddress": "إضافة عنوان",
  "account.editAddress": "تعديل العنوان",
  "account.addressAdded": "تمت إضافة العنوان.",
  "account.addressUpdated": "تم تحديث العنوان.",
  "account.addressDeleted": "تم حذف العنوان.",
  "account.confirmDelete": "هل أنت متأكد من حذف هذا العنوان؟",
  "account.maxAddresses": "يمكنك حفظ أكثر من عنوان للتوصيل.",
  "account.noAddresses": "لا توجد عناوين محفوظة بعد.",
  "account.label": "التسمية",
  "account.home": "المنزل",
  "account.office": "المكتب",
  "account.recipientName": "اسم المستلم",
  "account.postalCode": "الرقم البريدي",
  "account.setDefaultAddress": "تعيين كعنوان افتراضي",
  "account.backToOrders": "العودة إلى الطلبات",
  "account.statusHistory": "سجل الحالة",
  "account.paidOn": "تم الدفع في {date}",

  "general.loading": "جاري التحميل...",
  "general.error": "حدث خطأ ما",
  "general.retry": "إعادة المحاولة",
  "general.save": "حفظ التغييرات",
  "general.cancel": "إلغاء",
  "general.delete": "حذف",
  "general.edit": "تعديل",
  "general.close": "إغلاق",
  "general.back": "رجوع",
  "general.next": "التالي",
  "general.submit": "إرسال",
  "general.search": "بحث",
  "general.noResults": "لا توجد نتائج",
  "general.currency": "ج.م",
  "general.loadingShort": "جاري التحميل...",
  "general.whatsapp": "واتساب",
  "general.facebook": "فيسبوك",
  "general.instagram": "إنستجرام",
  "general.breadcrumb": "مسار التنقل",
  "general.closeCart": "إغلاق السلة",
  "general.removeItem": "إزالة العنصر",
  "general.decreaseQuantity": "تقليل الكمية",
  "general.increaseQuantity": "زيادة الكمية",
  "general.chatOnWhatsApp": "تحدث عبر واتساب",
  "general.toggleMenu": "فتح أو إغلاق القائمة",
  "general.product": "منتج",
  "general.quantityShort": "الكمية",
  "general.select": "اختر",
  "general.other": "أخرى",
  "general.pending": "قيد الانتظار",

  "footer.quickLinks": "روابط سريعة",
  "footer.services": "الخدمات",
  "footer.contactInfo": "معلومات الاتصال",
  "footer.copyright": "© ٢٠٢٦ لورد لتكييف الهواء",
  "footer.allRights": "جميع الحقوق محفوظة.",
  "footer.description":
    "وكيل معتمد لكاريير وميديا. حلول تكييف الهواء منذ ١٩٨٦.",
  "footer.service.installation": "التركيب",
  "footer.service.maintenance": "الصيانة",
  "footer.service.repair": "الإصلاح",
  "footer.service.delivery": "التوصيل",
  "footer.service.spareParts": "قطع الغيار",
  "legal.privacyPolicy": "سياسة الخصوصية",
  "legal.termsConditions": "الشروط والأحكام",

  "services.title": "خدماتنا",
  "services.tagline": "دعم ما بعد البيع الكامل لتكييف الهواء الخاص بك",
  "services.subtitle": "تركيب وصيانة وإصلاح ودعم من متخصصي لورد.",
  "services.requestService": "طلب هذه الخدمة",
  "services.urgentCta": "تحتاج خدمة عاجلة؟ اتصل بنا الآن",
  "services.ctaTitle": "تحتاج مساعدة في التكييف؟",
  "services.ctaSubtitle": "أرسل طلب خدمة وسيتواصل معك فريقنا.",
  "services.chatWhatsApp": "تواصل عبر واتساب",
  "services.requestSubmitted": "تم إرسال طلب الخدمة",
  "services.requestDesc": "استلمنا طلبك وسنتواصل معك قريباً.",
  "services.submitAnother": "إرسال طلب آخر",
  "services.requestFormDesc": "أخبرنا بما تحتاجه وسنرتب الدعم المناسب.",
  "services.serviceType": "نوع الخدمة",
  "services.acBrand": "علامة التكييف",
  "services.installationAddress": "عنوان التركيب",
  "services.preferredDate": "التاريخ المفضل",
  "services.description": "الوصف",
  "services.descriptionPlaceholder": "اكتب المشكلة أو الخدمة المطلوبة...",
  "services.submitRequest": "إرسال الطلب",
  "services.selectServiceType": "اختر نوع الخدمة",
  "services.selectBrand": "اختر العلامة",
  "services.otherBrand": "أخرى",
  "services.installationAddressPlaceholder": "عنوان التركيب بالكامل",

  "contact.title": "اتصل بنا",
  "contact.sendMessage": "إرسال الرسالة",
  "contact.thankYou": "شكراً لك! سنتواصل معك خلال ساعة واحدة.",
  "contact.getDirections": "الحصول على الاتجاهات",
  "contact.subtitle": "نحن هنا للمساعدة في المنتجات والتركيب والصيانة والدعم.",
  "contact.address": "العنوان",
  "contact.phone": "الهاتف",
  "contact.whatsapp": "واتساب",
  "contact.email": "البريد الإلكتروني",
  "contact.workingHours": "ساعات العمل",
  "contact.formTitle": "أرسل لنا رسالة",
  "contact.name": "الاسم",
  "contact.namePlaceholder": "اسمك بالكامل",
  "contact.emailPlaceholder": "you@example.com",
  "contact.inquiryType": "نوع الاستفسار",
  "contact.inquiryTypes.general": "استفسار عام",
  "contact.inquiryTypes.purchase": "شراء",
  "contact.inquiryTypes.installation": "تركيب",
  "contact.inquiryTypes.maintenance": "صيانة",
  "contact.inquiryTypes.orderSupport": "دعم الطلبات",
  "contact.message": "الرسالة",
  "contact.messagePlaceholder": "كيف يمكننا مساعدتك؟",
  "contact.send": "إرسال الرسالة",
  "contact.successMessage": "تم إرسال الرسالة بنجاح.",
  "contact.errorMessage": "تعذر إرسال الرسالة. حاول مرة أخرى.",
  "contact.mapTitle": "موقع لورد",

  "faq.title": "الأسئلة الشائعة",
  "faq.cantFind": "لم تجد إجابتك؟",
  "faq.subtitle": "إجابات لأكثر الأسئلة شيوعاً عن المنتجات والتركيب والدعم.",
  "faq.searchPlaceholder": "ابحث في الأسئلة...",
  "faq.ctaTitle": "ما زلت تحتاج مساعدة؟",
  "faq.ctaSubtitle": "تواصل مع فريقنا وسنساعدك في اختيار الحل المناسب.",
  "faq.chatWithUs": "تحدث معنا",

  "order.confirmed": "مؤكد",
  "order.processing": "قيد المعالجة",
  "order.shipped": "تم الشحن",
  "order.delivered": "تم التسليم",
  "order.cancelled": "ملغي",
  "order.refunded": "مسترد",
  "order.pendingPayment": "في انتظار الدفع",
  "order.orderPlaced": "تم استلام الطلب",
  "order.cancelOrder": "إلغاء الطلب",
  "order.trackOrder": "تتبع طلبي",
  "order.enterOrderId": "أدخل رقم الطلب",
  "order.track": "تتبع",
  "order.trackDesc": "أدخل رقم الطلب لعرض آخر حالة له.",
  "order.notFound": "الطلب غير موجود",
  "order.items": "عناصر الطلب",

  "orderConfirmation.title": "تم تقديم الطلب بنجاح!",
  "orderConfirmation.subtitle": "شكراً لطلبك. سنبقيك على اطلاع.",
  "orderConfirmation.orderId": "رقم الطلب",
  "orderConfirmation.emailSent": "تم إرسال بريد التأكيد إلى",
  "orderConfirmation.estimatedDelivery": "موعد التسليم المتوقع: ٣-٥ أيام عمل",
  "orderConfirmation.continueShopping": "متابعة التسوق",
  "orderConfirmation.viewOrders": "عرض طلباتي",

  "about.title": "عن لورد",
  "about.subtitle": "حلول تكييف معتمدة وتركيب ودعم منذ ١٩٨٦.",
  "about.storyTitle": "قصتنا",
  "about.missionTitle": "مهمتنا",
  "about.visionTitle": "رؤيتنا",
  "about.authorizedTitle": "وكيل معتمد لكاريير وميديا",
  "about.authorizedDesc":
    "نوفر منتجات أصلية وتركيباً احترافياً ودعماً موثوقاً بعد البيع.",
  "about.yearsExperience": "سنوات خبرة",
  "about.happyCustomers": "عملاء سعداء",
  "about.governorates": "محافظات",
  "about.rating": "تقييم العملاء",
};

const translations: Record<Language, Translations> = { en, ar };

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [language, setLanguageState] = useState<Language>("en");

  useEffect(() => {
    const saved = Cookies.get("lord_language") as Language | undefined;
    if (saved && (saved === "en" || saved === "ar")) {
      setLanguageState(saved);
      document.documentElement.lang = saved;
      document.documentElement.dir = saved === "ar" ? "rtl" : "ltr";
    }
  }, []);

  const setLanguage = useCallback((lang: Language) => {
    setLanguageState(lang);
    Cookies.set("lord_language", lang, { expires: 365 });
    document.documentElement.lang = lang;
    document.documentElement.dir = lang === "ar" ? "rtl" : "ltr";
  }, []);

  const t = useCallback(
    (key: string): string => {
      return translations[language][key] || key;
    },
    [language],
  );

  const localize = useCallback(
    (english?: string | null, arabic?: string | null): string => {
      if (language === "ar") return arabic?.trim() || english?.trim() || "";
      return english?.trim() || arabic?.trim() || "";
    },
    [language],
  );

  const dir = language === "ar" ? "rtl" : "ltr";
  const isRTL = language === "ar";

  return (
    <LanguageContext.Provider
      value={{ language, setLanguage, t, localize, dir, isRTL }}
    >
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error("useLanguage must be used within a LanguageProvider");
  }
  return context;
}
